### ISSUE TITLE
Fix treasure type (A-R) promise issue

### ISSUE THREAD

**Issue by dricard** [AutarchLLC/foundryvtt-acks-core#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dricard** [comment]
Reported by Bark on Discord

**Comment by dasBarkman** [comment]
To Reproduce
Steps to reproduce the behavior:

Go to compendium packs
Click on 'ACKS Treasure Tables'
Scroll past the working Magic item tables 
Click on any of the treasure types (A-R, individual lists)
Click on Roll Treasure. 
Results expected in Chat 


See error
Error - roll results show Treasure Type A, and results of 'object promise'

Expected behavior
Roll against treasure type appears in chat..
See Results of Magic item Tables above.

Screenshots
Treasure Type A
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/165521079/36b2679f-0120-4e7b-b01d-d851ac89f10a)
Results
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/165521079/6b04466a-8053-4b90-b36a-bb7b2ca2fce1)
Potions table
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/165521079/60da1b80-72d9-4139-aee9-7f52f6d87c3e)
Potions Results
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/165521079/418179e2-5640-4f88-a7ea-f5be75c02442)


Desktop (please complete the following information):

OS:  Windows 10
Browser: Edge 
Version:  123.0.2420.65 (Official build) (64-bit)  (current latest)
