### ISSUE TITLE
Clicking spell roll in chat causes error

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#9]
**Describe the bug**
When clicking some spells' dice rolls, an error is produced.

Confirmed that this issue was present from the older ACKS code.

See solution comment below - https://github.com/AutarchLLC/foundryvtt-acks-core/issues/9#issuecomment-2016542386.

**Plan to Fix**
This bug should be addressed as part of the compendium rework.

**To Reproduce**
1. Create actor with at least 1 Spell: Sleep
2. Click on the spell's icon to roll it
3. The spell appears in the chat log
4. Click on the associated dice roller in the chat log
5. The error appears in the console

**Expected behavior**
The expected result is for a die roll to take place.

**Screenshots**
From Foundry v11:
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/31d35c82-89ae-4cb2-8a38-82019da41737)

From Foundry v9:
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/739f98cb-c13b-48ee-9b28-79d769950a71)

**Comment by LeRatierBretonnien** [comment]
This issue is already present in the v9 version. In this case, the roll formula is not a valid Foundry roll formula: 
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/1085008/9cf403c6-522b-473f-9f98-a1cab819bd67)

The 'HD' term is not understood by the Foundry roll engine, hence the error.

Solution : remove the 'HD' from the roll formula in this spell.

**Comment by ArcanistWill** [comment]
I am closing this issue because all of the current spells in the compendium have to be revised to update them for ACKS II. During that process we should also fix any rolls that are present.

There is no point keeping this open.
